# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

env:
  RENV_PATHS_ROOT: ~/.local/share/renv

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          
      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install libcurl
        run: sudo apt-get install libcurl4-openssl-dev
      
#      - name: Install pdflatex
#        run: |
#          sudo apt-get install texlive-latex-extra        
        
      - name: Install pandoc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
          brew install curl
          
      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'
       
      - name: Render the presentations
        run: |
          R -e 'rmarkdown::render("presentations/1_Intro/intro_to_r.Rmd", output_dir = "pages")'
          R -e 'rmarkdown::render("presentations/2_Data_Structures_Functions/data_structures_and_functions.Rmd", output_dir = "pages")'
          R -e 'rmarkdown::render("presentations/3_Tidyverse/tidyverse.Rmd", output_dir = "pages")'
          R -e 'rmarkdown::render("presentations/4_Data_Analysis/data_analysis.Rmd", output_dir = "pages")'
          
      # Deploys the files to GitHubPages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: pages # The folder the action should deploy.
          CLEAN: FALSE # Automatically remove deleted files from the deploy branch
